version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "/home/jim/project/dev_env/mysql/data:/var/lib/mysql"
      - "/home/jim/project/dev_env/mysql/conf:/etc/mysql"
      - "/home/jim/project/dev_env/mysql/log:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_USER: "test"
#      MYSQL_PASSWORD: "test"
#    command: mysqld --init-file="/tmp/mysql/init/init.sql"
#    network_mode: "host"
  swagger-service:
    image: zhengcj01/swagger
    container_name: swagger-service
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:mysql
    environment:
      - spring.profiles.active=dev
